const indianNames = [
  "Aarav",
  "Vivaan",
  "Aditya",
  "Vihaan",
  "Arjun",
  "Sai",
  "Reyansh",
  "Krishna",
  "Ishaan",
  "Shaurya",
  "Ayaan",
  "Dhruv",
  "Kabir",
  "Ananya",
  "Aditi",
  "Diya",
  "Ishita",
  "Meera",
  "Anika",
  "Riya",
  "Sneha",
  "Saanvi",
  "Tara",
  "Pooja",
  "Kavya",
  "Mira",
  "Tanvi",
  "Nisha",
  "Priya",
  "Radha",
  "Ashwin",
  "Raghav",
  "Anand",
  "Karthik",
  "Rishi",
  "Rajesh",
  "Suresh",
  "Vikram",
  "Harish",
  "Kamal",
  "Geeta",
  "Lakshmi",
  "Sunita",
  "Pallavi",
  "Chitra",
  "Komal",
  "Rupal",
  "Varsha",
  "Seema",
  "Neeta",
  "Amit",
  "Rahul",
  "Rohan",
  "Vishal",
  "Manoj",
  "Sanjay",
  "Arun",
  "Raj",
  "Ajay",
  "Nitin",
  "Sonal",
  "Deepa",
  "Shilpa",
  "Rashmi",
  "Meghna",
  "Leela",
  "Uma",
  "Bhavna",
  "Jaya",
  "Preeti",
  "Vivek",
  "Ravindra",
  "Pranav",
  "Siddharth",
  "Himanshu",
  "Vikrant",
  "Tarun",
  "Akash",
  "Bhavesh",
  "Naveen",
  "Jyoti",
  "Anjali",
  "Ritika",
  "Sheetal",
  "Monika",
  "Usha",
  "Savita",
  "Kiran",
  "Sarita",
  "Vandana",
  "Neeraj",
  "Yash",
  "Kunal",
  "Abhishek",
  "Prateek",
  "Omkar",
  "Keshav",
  "Arvind",
  "Jitendra",
  "Ravish",
  "Mamta",
  "Kajal",
  "Payal",
  "Nandini",
  "Harini",
  "Sushma",
  "Anusha",
  "Rekha",
  "Sapna",
  "Sakshi",
  "Ganesh",
  "Prakash",
  "Shankar",
  "Ramesh",
  "Harsha",
  "Venkatesh",
  "Naresh",
  "Mahesh",
  "Dinesh",
  "Mohan",
  "Smita",
  "Sudha",
  "Sangeeta",
  "Radha",
  "Vaishnavi",
  "Anuradha",
  "Shobha",
  "Shivani",
  "Swati",
  "Bhumika",
  "Kiran",
  "Lokesh",
  "Manish",
  "Akhil",
  "Rajiv",
  "Satyam",
  "Saurabh",
  "Aman",
  "Varun",
  "Yuvraj",
  "Charu",
  "Neha",
  "Poonam",
  "Meenal",
  "Harini",
  "Amrita",
  "Archana",
  "Lata",
  "Pushpa",
  "Kalpana",
  "Ravi",
  "Bhanu",
  "Gopal",
  "Suraj",
  "Ashok",
  "Subhash",
  "Dev",
  "Narayan",
  "Sachin",
  "Vijay",
  "Parvati",
  "Gayatri",
  "Bina",
  "Kamini",
  "Manju",
  "Ragini",
  "Tina",
  "Kusum",
  "Naina",
  "Alka",
  "Rohit",
  "Tejas",
  "Devendra",
  "Aniket",
  "Adarsh",
  "Hemant",
  "Mayur",
  "Inder",
  "Niraj",
  "Sanjiv",
  "Madhuri",
  "Priyanka",
  "Rupali",
  "Siddhi",
  "Veena",
  "Kalindi",
  "Anushka",
  "Namrata",
  "Varsha",
  "Shanti",
];

const youtubeComments = [
  "Great video, loved it!",
  "This was super helpful, thanks!",
  "Amazing content as always!",
  "Can you make a video about this topic?",
  "I learned so much from this, thank you!",
  "This is exactly what I needed!",
  "The editing on this video is top-notch.",
  "Wow, I didn’t know that before!",
  "Keep up the great work!",
  "Who else is watching this in 2025?",
  "This video deserves more views.",
  "Can’t wait for the next upload!",
  "I’ve been binge-watching your videos all day.",
  "Does anyone know the background music?",
  "This is so underrated.",
  "Thanks for breaking it down so clearly!",
  "I’ve subscribed. Looking forward to more!",
  "I’ve shared this with my friends.",
  "Can you link the resources you mentioned?",
  "This is pure gold!",
  "Laughed so hard at 2:34 😂",
  "When’s the next live stream?",
  "This was so inspiring.",
  "I’ve rewatched this video 5 times already.",
  "This deserves to go viral!",
  "How do you come up with these ideas?",
  "I appreciate the effort you put into this.",
  "I’m here before 1M views!",
  "Can someone explain the part at 3:45?",
  "This is my favorite channel!",
  "I didn’t expect that twist at the end!",
  "Thanks for the detailed explanation.",
  "This is why I love YouTube.",
  "The visuals in this video are stunning.",
  "I feel smarter after watching this.",
  "Keep pushing out amazing content!",
  "Does anyone know what camera they use?",
  "This video made my day.",
  "Your enthusiasm is contagious!",
  "I’ve been waiting for this video all week.",
  "This should be a series!",
  "Can you pin my comment? 😊",
  "This community is so supportive!",
  "I’ve never clicked a video so fast.",
  "I can’t believe this is free content.",
  "How do you stay so consistent?",
  "This is better than Netflix!",
  "You’re so underrated, keep it up!",
  "This deserves an award.",
  "So many useful tips, thanks!",
  "You’ve gained a lifelong fan here.",
  "Can you explain the software you used?",
  "This is a masterpiece!",
  "Thanks for making complex topics simple.",
  "The timestamps are so helpful, thanks!",
  "I was smiling the whole time.",
  "This is the reason I love this platform.",
  "Your personality makes these videos shine!",
  "How do you edit your videos?",
  "This gave me so many ideas.",
  "I can’t stop recommending this channel.",
  "More videos like this, please!",
  "This is exactly what I was looking for.",
  "You have the best tutorials ever.",
  "This video helped me so much.",
  "Such a wholesome video!",
  "I’m so glad I found this channel.",
  "I love how you explain things.",
  "This is my go-to channel for this topic.",
  "Who else paused to take notes?",
  "This video is a gem.",
  "I wish I found this sooner.",
  "The effort you put in is commendable.",
  "This is such a creative idea!",
  "I love how engaging this is.",
  "I’m sharing this with everyone I know.",
  "This taught me more than my classes.",
  "I can’t thank you enough for this.",
  "This was an emotional rollercoaster.",
  "You deserve all the success coming your way.",
  "This video is so well-researched.",
  "Your energy is unmatched!",
  "This channel is my new obsession.",
  "You’ve outdone yourself with this one.",
  "This is next-level content.",
  "I’m in awe of your creativity.",
  "This is the best thing I’ve watched all day.",
  "I love the way you present information.",
  "I’ve been a fan since day one.",
  "This is what the internet was made for.",
  "I laughed so hard at 5:12!",
  "This should be shown in schools.",
  "You’ve made my week with this video.",
  "I can’t wait to implement these tips.",
  "This video is worth every second.",
  "You’ve raised the bar again.",
  "How can anyone dislike this?",
  "This is better than paid courses.",
  "I’m blown away by this video.",
  "This is why you’re my favorite YouTuber.",
  "This deserves all the likes in the world.",
  "I’ve learned so much from you.",
  "This is pure talent.",
  "You’re changing lives with these videos.",
  "This is the highlight of my day.",
  "I can’t wait to rewatch this.",
  "This video is perfection.",
  "I love how interactive this is.",
  "This is the best tutorial ever.",
  "Your dedication is inspiring.",
  "I’m so grateful for this content.",
  "This is the most helpful video on the topic.",
  "I’m amazed at how much I learned.",
  "This is a game-changer.",
  "I’ve never seen anything like this before.",
  "You’ve made a complex topic so simple.",
  "This video deserves a million views.",
  "I’m hooked on your content.",
  "This is a must-watch for everyone.",
  "Your positivity is infectious.",
  "This is content done right.",
  "I can’t stop rewatching this.",
  "Your hard work really shows.",
  "This is what quality content looks like.",
  "I feel so motivated after watching this.",
  "This video is pure art.",
  "I’m so impressed by this.",
  "This was so fun to watch.",
  "I love how informative this is.",
  "I’ve subscribed, and I’m here to stay.",
  "This is my favorite video on this topic.",
  "This is exactly what I needed today.",
  "You’re an inspiration to all creators.",
  "This is content I’ll keep coming back to.",
  "I’ve shared this with my entire team.",
  "This is what makes this channel stand out.",
  "I can’t stop smiling after this video.",
  "This is why I keep coming back to your channel.",
  "This deserves a standing ovation.",
  "I’ve bookmarked this for later.",
  "This is a work of art.",
  "You’ve set a new standard with this video.",
  "This is why you’re the best.",
  "This video is packed with value.",
  "I can’t believe how much I learned from this.",
  "This is the type of content I live for.",
];

export const generateRandomComment = () => {
  const commentObj = {
    person: indianNames[Math.floor(Math.random() * indianNames.length)],
    comment:
      youtubeComments[Math.floor(Math.random() * youtubeComments.length)],
  };
  return commentObj;
};
